title: Data Science course
author: Leonid Dybovskii

execute:
  execute_notebooks: 'off'

repository:
  url: https://github.com/LeonidDybovskij/yandex 

html:
  use_issues_button: false
  use_repository_button: false
